name: Deploy static site to Azure Web App
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is REQUIRED for OIDC
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP package of site
        run: |
          zip -r site.zip . -x ".git/*" ".github/*" "node_modules/*"

     - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BomajPharmaceutical'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ./site.zip
          # ðŸš¨ Do NOT add 'auth-type' for OIDC login

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BomajPharmaceutical'
          package: site.zip

